/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3WMttyXUq",
    "aws_user_pools_web_client_id": "4dv1rhbqqp8sm4rj0mjretg1k0",
    "oauth": {}
};


export default awsmobile;
